### PR TITLE
bugfix duplicate files

### PR DESCRIPTION
**Pull request by leason00**
Signed-off-by: lisen <lisen@youzan.com>

### CODE REVIEW

**Comment by leason00** [comment]
@zzxwill

**Comment by chivalryq** [comment]
Can you explain how did this cause the bug?

**Comment by leason00** [comment]
docker build --platform linux/amd64 -t oamdev/docker-terraform:1.1.8.test . --build-arg PROVIDERS=tencentcloudstack/tencentcloud/1.72.8,huaweicloud/huaweicloud/1.38.0
image

**Review by chivalryq — APPROVED** [review]
LGTM, nice catch!

**Review by wonderflow — APPROVED** [review]

**Pull request merged**
